/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplication;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Login extends javax.swing.JFrame {

    File f = new File("C:\\ProyectoJulioyStiven");
    int ln;
    String Username,Password,Admin;
    
    /**
     * Creates new form notepad
     */
    public Login() {  
        initComponents();
        this.setLocationRelativeTo(null);
    }

    void createFolder(){
        if(!f.exists()){
            f.mkdirs();
        }
    }
    
    
    
    public void readFile(){
        try {
            FileReader fr = new FileReader(f+"\\logins.txt");
            System.out.println("Archivo Existente!");
        } catch (FileNotFoundException ex) {
            try {
                FileWriter fw = new FileWriter(f+"\\logins.txt");
                
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write("Stiven,123#St,Asesor");
            bw.close();
                System.out.println("Archivo Creado");
            } catch (IOException ex1) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
        
    }
    
    private static Scanner x;
    
    String filepath = "C:\\ProyectoJulioyStiven\\logins.txt";
    
    public  void verificar (String username, String password,String tipo ,String filepath){
        boolean found = false;
        String TempUsername = "";
        String TempPassword = "";
        String tipotemp = "";
        
        String Admin_User_Base = "juls";
        String Admin_Pass_Base = "Zte22#1";
        
        
        try {
            x = new Scanner(new File(filepath));
            x.useDelimiter("[,\n]");
            
            while (x.hasNext() && !found) {
                TempUsername = x.next();
                TempPassword = x.next();
                tipotemp     = x.next();
                
                if (TempUsername.trim().equals(username.trim()) && TempPassword.trim().equals(password.trim()) && tipotemp.trim().equals(tipo.trim())){
                    found = true;
                    
                    if (tipo == "Administrador"){
                        Intermedio V5 = new Intermedio();
                        V5.setVisible(true);
                        this.setVisible(false);
                        JOptionPane.showMessageDialog(null, "Administrador " + username + " Inicio sesion");
                    }
                    else {
                        IntermedioAsesor V6 = new IntermedioAsesor();
                        V6.setVisible(true);
                        this.setVisible(false);
                        JOptionPane.showMessageDialog(null, "Asesor " + username + " Inicio sesion");
                    }
                    
                }
                else if (username.equals("juls") && password.equals("Zte22#1")) {
                    Intermedio V5 = new Intermedio();
                    V5.setVisible(true);
                    this.setVisible(false);
                    JOptionPane.showMessageDialog(null, "Administrador " + username + " Inicio sesion");
                    found = true;
                }
            }
            
            x.close();
            if (found == false){
                JOptionPane.showMessageDialog(null, "Datos invalidos");
            }
        } catch (Exception e) {
            System.out.println("Error");
        }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfusr = new javax.swing.JTextField();
        tfmail1 = new javax.swing.JComboBox<>();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        tfmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 110, 38));

        jButton3.setText("clear all");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 100, 38));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Iniciar Sesion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 22, 230, 45));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 112, 44));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 112, 43));

        tfusr.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        getContentPane().add(tfusr, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 150, 44));

        tfmail1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Asesor" }));
        getContentPane().add(tfmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 120, -1));

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 150, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/geometria-3d-3586.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-320, 0, 830, 370));

        tfmail.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tfmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfmailActionPerformed(evt);
            }
        });
        getContentPane().add(tfmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 197, 129, 42));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Clave Admin");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 197, 112, 42));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        createFolder(); 
        readFile();
        String valorPass = "";
        for (int i = 0; i < jPasswordField1.getPassword().length; i++) {
            valorPass += jPasswordField1.getPassword()[i];
        }
        verificar(tfusr.getText(), valorPass,(String)tfmail1.getSelectedItem() ,filepath);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        tfusr.setText("");     
        jPasswordField1.setText("");
        tfmail.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    
    
    
    private void tfmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfmailActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField tfmail;
    private javax.swing.JComboBox<String> tfmail1;
    private javax.swing.JTextField tfusr;
    // End of variables declaration//GEN-END:variables
}
